# Generated by Django 3.2.5 on 2021-08-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_delete_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='task',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
