# Generated by Django 3.2.5 on 2021-08-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_userdetails_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='fname',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lname',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
