# Generated by Django 3.2.5 on 2021-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210815_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='task',
        ),
    ]
