# Generated by Django 3.2.5 on 2021-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210815_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='username',
            field=models.CharField(default=True, max_length=122),
            preserve_default=False,
        ),
    ]
